import os
import json
import mido
from mido import Message, MidiFile, MidiTrack, MetaMessage


class Exporter:
    def __init__(self):
        pass

    def export_midi(self, analysis_data, output_path):
        """
        解析データ(JSON)からMIDIファイルを生成する
        """
        mid = MidiFile()
        ticks_per_beat = 480
        mid.ticks_per_beat = ticks_per_beat

        # テンポ情報の取得 (drums > bass > vocals の優先順で探す)
        tempo_bpm = 120.0
        for stem in ["drums", "bass", "vocals", "other"]:
            if stem in analysis_data and "audio_features" in analysis_data[stem]:
                t = analysis_data[stem]["audio_features"].get("tempo")
                if t:
                    tempo_bpm = float(t)
                    break
        
        # テンポトラック作成
        tempo_track = MidiTrack()
        mid.tracks.append(tempo_track)
        tempo_micro = mido.bpm2tempo(tempo_bpm)
        tempo_track.append(MetaMessage('set_tempo', tempo=tempo_micro, time=0))
        tempo_track.append(MetaMessage('time_signature', numerator=4, denominator=4, time=0))

        # 各ステムごとのトラック作成
        instrument_map = {
            "vocals": 52,
            "bass": 33,
            "piano": 0,
            "guitar": 27,
            "other": 81,
            "drums": 0
        }

        channels = {
            "vocals": 0,
            "piano": 1,
            "guitar": 2,
            "bass": 3,
            "other": 4,
            "drums": 9
        }

        for stem_name, stem_data in analysis_data.items():
            if stem_name not in instrument_map:
                continue

            track = MidiTrack()
            mid.tracks.append(track)
            track.append(MetaMessage('track_name', name=stem_name.capitalize(), time=0))
            
            channel = channels.get(stem_name, 0)
            program = instrument_map.get(stem_name, 0)
            
            if channel != 9:
                track.append(Message('program_change', channel=channel, program=program, time=0))

            events = []

            if "melody" in stem_data and stem_data["melody"]:
                for m in stem_data["melody"]:
                    note_num = int(round(m["midi"]))
                    if note_num < 0 or note_num > 127: continue
                    
                    start_time = float(m["time"])
                    duration = 0.1
                    
                    start_tick = int(start_time * (tempo_bpm / 60) * ticks_per_beat)
                    end_tick = int((start_time + duration) * (tempo_bpm / 60) * ticks_per_beat)
                    
                    events.append({"type": "note_on", "note": note_num, "velocity": 100, "tick": start_tick, "channel": channel})
                    events.append({"type": "note_off", "note": note_num, "velocity": 0, "tick": end_tick, "channel": channel})

            elif "chords" in stem_data and stem_data["chords"]:
                note_map = {"C": 0, "C#": 1, "D": 2, "D#": 3, "E": 4, "F": 5, "F#": 6, "G": 7, "G#": 8, "A": 9, "A#": 10, "B": 11}
                
                for c in stem_data["chords"]:
                    start_time = float(c["time"])
                    duration = 0.5
                    
                    start_tick = int(start_time * (tempo_bpm / 60) * ticks_per_beat)
                    end_tick = int((start_time + duration) * (tempo_bpm / 60) * ticks_per_beat)
                    
                    for note_name in c["notes"]:
                        base_val = note_map.get(note_name[:-1] if len(note_name)>1 and note_name[-1].isdigit() else note_name, 0)
                        octave = 2 if stem_name == "bass" else 4
                        note_num = base_val + (octave + 1) * 12
                        
                        events.append({"type": "note_on", "note": note_num, "velocity": 80, "tick": start_tick, "channel": channel})
                        events.append({"type": "note_off", "note": note_num, "velocity": 0, "tick": end_tick, "channel": channel})

            events.sort(key=lambda x: x["tick"])
            
            last_tick = 0
            for e in events:
                delta = e["tick"] - last_tick
                if delta < 0: delta = 0
                track.append(Message(e["type"], note=e["note"], velocity=e["velocity"], time=delta, channel=e["channel"]))
                last_tick = e["tick"]

        mid.save(output_path)
        return output_path

    def generate_report(self, analysis_data):
        """
        解析データから「専門家のような」テキストレポートを生成
        """
        lines = []
        lines.append("=== AINOMIMI AUDIO ANALYSIS REPORT ===")
        lines.append(f"Generated by AINOMIMI: The Critic")
        lines.append("="*40)
        lines.append("")

        # 1. マスター音源全体解析 (2mix)
        master_summary = self._format_master_mix_summary(analysis_data)
        if master_summary:
            lines.append("## 1. マスター音源全体 (Full Mix Analysis)")
            lines.append(master_summary)
            lines.append("")

        # 2. 検出サマリー (AudioSet)
        audioset_summary = self._format_audioset_summary(analysis_data)
        if audioset_summary:
            lines.append("## 2. 検出サマリー (AudioSet Deep Scan)")
            lines.append(audioset_summary)
            lines.append("")

        # 3. VOCAL & LYRICS (ボーカル・歌詞詳細)
        if "vocals" in analysis_data:
            lines.append("## 3. ボーカル・プロファイリング (Vocal & Lyrical Profile)")
            lines.append(self._analyze_vocal_profile(analysis_data["vocals"]))
            lines.append("")

        # 4. STRUCTURE & ARRANGEMENT (構成と展開)
        if "structure" in analysis_data:
            lines.append("## 4. 楽曲構成と展開 (Structure & Arrangement)")
            lines.append(self._analyze_structure_breakdown(analysis_data))
            lines.append("")

        # 5. TRACK BY TRACK (パート別解説)
        lines.append("## 5. パート別詳細解析 (Track Breakdown)")
        
        # 全体ジャンルを集計（異色ステムのみ表示するため）
        overall_genres = self._get_overall_genre_set(analysis_data)

        for stem in ["bass", "drums", "guitar", "piano", "other"]:
            if stem in analysis_data:
                lines.append(f"\n### 【 {stem.upper()} 】")
                lines.append(self._analyze_stem_character(stem, analysis_data[stem], overall_genres))
        lines.append("")

        # 6. EXPERT PERSPECTIVES (専門家視点)
        lines.append("## 6. 専門家による多角的分析 (Expert Perspectives)")
        
        # Engineer
        eng_view = self._collect_engineer_views(analysis_data)
        if eng_view:
            lines.append("\n### 🎧 Sound Engineer's Ear (エンジニアの耳)")
            lines.extend(eng_view)
            
        # Arranger
        arr_view = analysis_data.get("structure", {}).get("arranger_view")
        if arr_view:
            lines.append("\n### 🎼 Arranger's Eye (アレンジャーの眼)")
            lines.append(f"- **構成タイプ**: {arr_view.get('arrangement_type', '?')}")
            lines.append(f"- **ドラマチック度**: {arr_view.get('drama_level', '?')}/100")
            lines.append(f"  → {arr_view.get('structural_notes', '')}")

        # Lyricist
        script = analysis_data.get("lyric_script")
        if script:
            lines.append("\n### 🖋️ Lyricist's Soul (作詞家の魂 - 構成脚本)")
            lines.append(script)

        # AI Prompter
        ai_p = analysis_data.get("ai_prompts")
        if ai_p:
            lines.append("\n### 🤖 AI Reverse Engineer (生成AIプロンプト)")
            lines.append(f"- **Suno/Udio Prompt**: \n  `{ai_p.get('suno_style', '')}`")
            lines.append(f"- **Recommended Tags**: {', '.join(ai_p.get('tags', []))}")

        # 7. VOICE PROFILE (汎用音声プロファイリング)
        profile = analysis_data.get("voice_profile", {})
        if profile and "error" not in profile:
            lines.append("")
            lines.append("## 7. 音声プロファイリング (Voice Profile)")
            lines.append(self._format_voice_profile(profile))

        lines.append("")
        lines.append("="*40)
        lines.append("End of Report")

        return "\n".join(lines)

    def _collect_engineer_views(self, data):
        """全ステムからエンジニアのメモを収集"""
        notes = []
        # マスターを優先
        mm_eng = data.get("master_mix", {}).get("audio_features", {}).get("engineer_view") # Wait, I added it to timbre
        # Actually I added it to each stem's timbre
        
        for stem in ["master_mix", "vocals", "bass", "drums", "other"]:
            stem_data = data.get(stem, {})
            # master_mix は直下に audio_features がある
            if stem == "master_mix":
                # Master mix doesn't have 'timbre' in my analyst.py implementation yet, let's check
                pass
            
            eng = stem_data.get("timbre", {}).get("engineer_view")
            if eng:
                notes.append(f"- **{stem.upper()}**: {eng['balance']} | {eng['spatial_feel']} | {eng['dynamics_impact']}")
                notes.append(f"  * {eng['technical_notes']}")
        return notes

    def _generate_overall_review(self, data):
        """全体的なジャンル感やミックスの矛盾などを指摘する"""
        # master_mix の AudioSet を最優先
        mm = data.get("master_mix", {})
        mm_aset = mm.get("audioset", {})
        if isinstance(mm_aset, dict) and "genres" in mm_aset and mm_aset["genres"]:
            labels = [g["label"] for g in mm_aset["genres"][:5]]
            review = f"マスター音源の全体解析により、この楽曲には **{', '.join(labels)}** の要素が検出されました。"
            if len(labels) >= 3:
                review += " 複数ジャンルが交差する **クロスオーバー/ミクスチャー** 的な性質を強く持っています。"
            # キー情報
            mm_af = mm.get("audio_features", {})
            key_info = mm_af.get("key", {})
            if key_info and "label" in key_info:
                review += f"\n推定キー: **{key_info['label']}** (confidence: {key_info.get('confidence', '?')})"
            return review

        # フォールバック: ステム側の AudioSet
        audioset_genres = []
        for stem in data.values():
            if isinstance(stem, dict) and "audioset" in stem:
                aset = stem["audioset"]
                if isinstance(aset, dict) and "genres" in aset:
                    audioset_genres.extend([g["label"] for g in aset["genres"]])

        if audioset_genres:
            from collections import Counter
            counts = Counter(audioset_genres)
            top_labels = [label for label, _ in counts.most_common(5)]
            return f"AudioSet詳細分析により、この楽曲には **{', '.join(top_labels)}** の要素が検出されました。"

        return "ジャンル判定不能な、前衛的な楽曲です。"

    def _format_master_mix_summary(self, data):
        """マスター音源(2mix)全体解析のサマリー"""
        mm = data.get("master_mix", {})
        if not mm or "error" in mm:
            return None

        lines = []
        af = mm.get("audio_features", {})
        if isinstance(af, dict) and "error" not in af:
            tempo = af.get("tempo", "?")
            lufs = af.get("lufs", "?")
            key_info = af.get("key", {})
            rhythm = af.get("rhythm_pattern", {})

            lines.append(f"🎵 **テンポ**: {tempo:.1f} BPM" if isinstance(tempo, (int, float)) else f"🎵 **テンポ**: {tempo}")
            if key_info:
                lines.append(f"🎹 **キー**: {key_info.get('label', '?')} (confidence: {key_info.get('confidence', '?')})")
            lines.append(f"📊 **LUFS**: {lufs} (知覚音圧)")
            if rhythm:
                lines.append(f"🥁 **リズム**: {rhythm.get('type', '?')} (regularity: {rhythm.get('regularity', '?')})")

        aset = mm.get("audioset", {})
        if isinstance(aset, dict) and "error" not in aset:
            genres = [g["label"] for g in aset.get("genres", [])[:5]]
            instruments = [i["label"] for i in aset.get("instruments", [])[:5]]
            if genres:
                lines.append(f"🏷️ **全体ジャンル感**: {', '.join(genres)}")
            if instruments:
                lines.append(f"🎸 **検出楽器**: {', '.join(instruments)}")

        return "\n".join(lines) if lines else None

    def _format_audioset_summary(self, data):
        """全ステムの AudioSet 結果を集約してサマリー文を生成"""
        all_genres, all_instruments, all_effects = [], [], []

        for stem_name, stem_data in data.items():
            if stem_name == "master_mix":  # master_mixは別セクションで表示
                continue
            if not isinstance(stem_data, dict) or "audioset" not in stem_data:
                continue
            aset = stem_data["audioset"]
            if isinstance(aset, dict) and "error" not in aset:
                all_genres.extend([g["label"] for g in aset.get("genres", [])])
                all_instruments.extend([i["label"] for i in aset.get("instruments", [])])
                all_effects.extend([e["label"] for e in aset.get("effects", [])])

        if not all_genres and not all_instruments and not all_effects:
            return None

        lines = []
        if all_genres:
            unique = list(dict.fromkeys(all_genres))
            lines.append(f"🏷️ **ステム詳細ジャンル**: {', '.join(unique)}")
        if all_instruments:
            unique = list(dict.fromkeys(all_instruments))
            lines.append(f"🎸 **検出楽器**: {', '.join(unique)}")
        if all_effects:
            unique = list(dict.fromkeys(all_effects))
            lines.append(f"🎛️ **エフェクト・奏法**: {', '.join(unique)}")

        return "\n".join(lines)

    def _analyze_world_view(self, data):
        """世界観プロファイリング"""
        if "vocals" not in data or "lyrics" not in data["vocals"]:
            return ""
            
        lyrics = data["vocals"]["lyrics"].get("full_text", "")
        if not lyrics: return ""
        
        positive_words = ["love", "dream", "hope", "未来", "愛", "夢", "希望", "好き"]
        negative_words = ["hate", "pain", "die", "kill", "嫌", "痛", "死", "殺", "クソ", "バカ"]
        aggressive_words = ["fight", "break", "shout", "戦", "壊", "叫", "オラ", "コラ"]
        
        score = 0
        aggro = 0
        for w in positive_words: score += lyrics.count(w)
        for w in negative_words: score -= lyrics.count(w)
        for w in aggressive_words: aggro += lyrics.count(w)
        
        sentiment = "Neutral"
        if aggro > 2: sentiment = "Aggressive/Provocative"
        elif score > 2: sentiment = "Positive/Uplifting"
        elif score < -2: sentiment = "Negative/Melancholic"
        
        bpm = 120
        if "drums" in data and "audio_features" in data["drums"]:
            bpm = data["drums"]["audio_features"].get("tempo", 120)
            
        mood = "落ち着いた" if bpm < 100 else "疾走感のある"
        if sentiment == "Aggressive/Provocative":
            return f"\n**【世界観 (World View)】**\n{mood}トラックに、**攻撃的で挑発的なメッセージ** を乗せた、反骨精神あふれる楽曲です。"
        elif sentiment == "Negative/Melancholic" and bpm > 110:
            return f"\n**【世界観 (World View)】**\nアップテンポな曲調とは裏腹に、**歌詞は内省的・悲観的** であり、そのギャップがエモーショナルな魅力を生んでいます（いわゆる『躁鬱ロック』的アプローチ）。"
        else:
             return f"\n**【世界観 (World View)】**\n歌詞の感情値は **{sentiment}** と判定されました。"

    def _analyze_vocal_profile(self, v_data):
        lines = []
        # AudioSetベースのボーカル特徴
        if "audioset" in v_data and isinstance(v_data["audioset"], dict):
            aset = v_data["audioset"]
            if aset.get("genres"):
                top_genre = aset["genres"][0]["label"]
                lines.append(f"- **Voice Type**: {top_genre} 風のアプローチ")
            
        if "vocal_style" in v_data:
            style = v_data["vocal_style"]
            desc = ""
            if style["style"] == "Airy/Whisper":
                desc = "息成分が多く、囁くような、あるいはアンニュイな歌唱法です。"
            elif style["style"] == "Expressive/Emotional":
                desc = "ダイナミクスの起伏が激しく、感情を爆発させるような表現力があります。"
            elif style["style"] == "Flat/Robotic":
                desc = "抑揚を抑えた、ロボットやオートチューンボイスのような無機質なスタイルです。"
                
            lines.append(f"- **Singing Style**: **{style['style']}**\n  → {desc}")
            lines.append(f"- **Technique**: Vibrato/Pitch Stability = {1.0 - style.get('dynamics_volatility',0)*100:.1f}/100")

        if "melody" in v_data:
            notes = [m["midi"] for m in v_data["melody"]]
            if notes:
                width = max(notes) - min(notes)
                lines.append(f"- **Range**: {width:.1f} semitones (Note count: {len(notes)})")

        return "\n".join(lines)

    def _analyze_structure_breakdown(self, data):
        """楽曲のセクションごとの展開を解説"""
        structure = data.get("structure")
        if not structure or isinstance(structure, dict):
            return "構造解析データが不足しています。"

        lines = []
        lines.append("推定された楽曲構成に基づき、各セクションの展開を解説します。")
        
        for i, section in enumerate(structure):
            label = section["label"]
            start = section["start"]
            end = section["end"]
            
            lines.append(f"\n### 🕒 {start:.1f}s - {end:.1f}s : {label}")
            
            if "drums" in data and "audio_features" in data["drums"]:
                stem_chords = data.get("guitar", {}).get("chords", [])
                section_chords = [c for c in stem_chords if start <= c["time"] < end]
                if section_chords:
                    unique_chords = []
                    prev = None
                    for c in section_chords:
                        cn = c["notes"][0] if c["notes"] else "?"
                        if cn != prev:
                            unique_chords.append(cn)
                            prev = cn
                    
                    if len(unique_chords) > 8:
                        unique_chords = unique_chords[:8] + ["..."]
                    
                    lines.append(f"- **Progression**: {' -> '.join(unique_chords)}")
            
            lines.append(f"- **Intensity**: この区間はエネルギーが高く、楽曲の盛り上がりポイント（サビ等）と推定されます。")

        return "\n".join(lines)

    def _get_overall_genre_set(self, data):
        """全体のジャンルセット (master_mix 優先) を返す"""
        genres = set()
        mm = data.get("master_mix", {})
        mm_aset = mm.get("audioset", {})
        if isinstance(mm_aset, dict) and "genres" in mm_aset:
            for g in mm_aset["genres"]:
                genres.add(g["label"].lower())
        if not genres:
            # フォールバック: ステムから集計
            for stem_data in data.values():
                if isinstance(stem_data, dict) and "audioset" in stem_data:
                    aset = stem_data["audioset"]
                    if isinstance(aset, dict) and "genres" in aset:
                        for g in aset["genres"]:
                            genres.add(g["label"].lower())
        return genres

    def _analyze_stem_character(self, stem_name, data, overall_genres=None):
        """各ステムの特性を言語化する (トラック別ジャンルは異色時のみ表示)"""
        comments = []
        
        # AudioSet 詳細 (genres: 異色時のみ / instruments / effects: 常に表示)
        if "audioset" in data and isinstance(data["audioset"], dict) and "error" not in data["audioset"]:
            aset = data["audioset"]

            # ジャンル: 全体と異なるものだけ表示
            if aset.get("genres") and overall_genres:
                unique_genres = [g for g in aset["genres"]
                                if g["label"].lower() not in overall_genres]
                if unique_genres:
                    labels = [f"{g['label']} ({int(g['score']*100)}%)" for g in unique_genres[:3]]
                    comments.append(f"- **異色ジャンル検出**: {', '.join(labels)}")

            if aset.get("instruments"):
                labels = [f"{i['label']}" for i in aset["instruments"][:5]]
                comments.append(f"- **Instruments**: {', '.join(labels)}")
            if aset.get("effects"):
                labels = [f"{e['label']}" for e in aset["effects"][:5]]
                comments.append(f"- **Effects / Techniques**: {', '.join(labels)}")

        # 音響特性 (Timbre)
        if "timbre" in data:
            t = data["timbre"]
            
            if "eq_balance" in t:
                eq = t["eq_balance"]
                low, mid, high = eq.get("low", 0), eq.get("mid", 0), eq.get("high", 0)
                
                char_text = ""
                if low > 0.5:
                    char_text = "圧倒的な低域(Low)が支配しており、楽曲の重厚な屋台骨となっています。"
                elif high > 0.4:
                    char_text = "高域(High)のエネルギーが非常に強く、煌びやかで「ヌケの良い」サウンドです。"
                elif mid > 0.6:
                    char_text = "中域(Mid)にエネルギーが集中しており、芯のある固い音作りです。"
                elif low > 0.35 and high > 0.35:
                    char_text = "低域と高域が強調された「ドンシャリ (V-Shape)」なモダンなミックスです。"
                else:
                    char_text = "全帯域がバランス良く整えられた、フラットで聞きやすい特性です。"
                
                comments.append(f"- **Sound Character**: {t.get('eq_character', 'Unknown')}\n  → {char_text}")

            if "spatial" in t:
                s = t["spatial"]
                dr = s.get("dynamic_range", 0)
                
                dyn_text = "音圧海苔に近い、コンプレッションの効いたパワー重視の音です。"
                if dr > 0.15:
                    dyn_text = "ダイナミックレンジが非常に広く、生演奏のようなグルーヴがあります。"
                elif dr > 0.08:
                    dyn_text = "適度な抑揚があり、聴き疲れしない健全なダイナミクスです。"
                
                comments.append(f"- **Dynamics**: Range={dr:.3f}\n  → {dyn_text}")
                
                env = s.get("shout_out", "Unknown")
                env_desc = "デッドでタイトなスタジオ録音の質感です。"
                if "Live" in env:
                    env_desc = "広がりと空気感があり、ライブ会場のような臨場感があります。"
                comments.append(f"- **Atmosphere**: {env}\n  → {env_desc}")

        # パート固有の音楽的詳細
        if stem_name == "vocals":
            if "melody" in data:
                notes = [m["midi"] for m in data["melody"]]
                if notes:
                    range_width = max(notes) - min(notes)
                    range_desc = "狭い音域で淡々と語るスタイル" if range_width < 12 else "非常に広い音域を使いこなす、感情的なパフォーマンス"
                    comments.append(f"- **Vocal Performance**: {len(notes)} notes detected.\n  → {range_desc} (Range: MIDI {min(notes):.1f}-{max(notes):.1f})")
            
            if "lyrics" in data and "full_text" in data["lyrics"]:
                txt = data["lyrics"]["full_text"]
                excerpt = txt[:60] + "..." if len(txt) > 60 else txt
                comments.append(f"- **Lyrical Content**:\n  > 「{excerpt}」")

        elif stem_name in ["guitar", "piano", "other"]:
            if "chords" in data:
                prog_len = len(data["chords"])
                prog_desc = "シンプルなループ中心" if prog_len < 20 else "頻繁に展開するプログレッシブな構成"
                comments.append(f"- **Harmony**: {prog_len} chord changes detected.\n  → {prog_desc}")

        # オーディオ特徴量の拡張情報
        if "audio_features" in data and isinstance(data["audio_features"], dict):
            af = data["audio_features"]
            key_info = af.get("key", {})
            rhythm = af.get("rhythm_pattern", {})
            if key_info and "label" in key_info:
                comments.append(f"- **Key**: {key_info['label']} (confidence: {key_info.get('confidence', '?')})")
            if rhythm and "type" in rhythm:
                comments.append(f"- **Rhythm**: {rhythm['type']} (regularity: {rhythm.get('regularity', '?')})")

        return "\n".join(comments)

    def _format_voice_profile(self, profile):
        """音声プロファイリング結果をASCIIバーとシグネチャで表示"""
        lines = []

        # インストルメント面
        inst = profile.get("instrument", {})
        if inst:
            lines.append("### 🎸 サウンド特性")
            axes = inst.get("axes", {})
            # INSTRUMENT_AXES の定義順で表示するためにprofilerからインポート
            try:
                from .profiler import INSTRUMENT_AXES
                for key, axis_def in INSTRUMENT_AXES.items():
                    val = axes.get(key, 0)
                    bar = self._make_bar(val)
                    lines.append(f"  {axis_def['name']:　<8} {bar} {val}")
            except ImportError:
                for k, v in axes.items():
                    bar = self._make_bar(v)
                    lines.append(f"  {k:　<16} {bar} {v}")
            lines.append(f"  **Overall**: {inst.get('overall', '?')}")
            if inst.get("signature"):
                lines.append(f"  💬 {inst['signature']}")

        # ボーカル面
        vocal = profile.get("vocal", {})
        if vocal:
            lines.append("\n### 🎤 ボーカル特性")
            axes = vocal.get("axes", {})
            try:
                from .profiler import VOCAL_AXES
                for key, axis_def in VOCAL_AXES.items():
                    val = axes.get(key, 0)
                    bar = self._make_bar(val)
                    lines.append(f"  {axis_def['name']:　<8} {bar} {val}")
            except ImportError:
                for k, v in axes.items():
                    bar = self._make_bar(v)
                    lines.append(f"  {k:　<16} {bar} {v}")
            lines.append(f"  **Overall**: {vocal.get('overall', '?')}")
            if vocal.get("signature"):
                lines.append(f"  💬 {vocal['signature']}")

        # 統合シグネチャ
        lines.append(f"\n### 📊 総合スコア: {profile.get('total_score', '?')}")
        sig = profile.get("combined_signature", "")
        if sig:
            lines.append(f"\n{sig}")

        return "\n".join(lines)

    def _make_bar(self, value, width=20):
        """0-100のスコアをASCIIバーで表現"""
        filled = int(value / 100 * width)
        return "█" * filled + "░" * (width - filled)
